
USE customer_behavior;
select * from customer limit 5;

-- *Customer & Revenue Analysis* --

-- Q1. What is the total revenue generated by male vs. female customers?
SELECT gender, SUM(purchase_amount) AS Total_Revenvue,
ROUND( 100* SUM(purchase_amount)/(SELECT SUM(purchase_amount) FROM customer),2) AS In_Percentage
FROM customer
GROUP by gender;

-- Q2. Which customers used a discount but still spent more than the average purchase amount?
SELECT customer_id, purchase_amount
FROM customer 
WHERE discount_applied = 'Yes' and purchase_amount > (SELECT AVG(purchase_amount) FROM customer);

-- Q3. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers
SELECT subscription_status, 
	count(customer_id)  AS "Total Customer",
	ROUND(AVG(purchase_amount), 3) AS "Average Purchase Amount",
	ROUND(SUM(purchase_amount), 3) AS "Total Revenue"
FROM customer
GROUP BY subscription_status;

-- Q4. Which category performs best in terms of sales, revenue, and average purchase value?
SELECT category, 
	COUNT(customer_id) AS "Total_sales", 
	ROUND(SUM(purchase_amount), 2) AS "Total_Revenue", 
	ROUND(AVG(purchase_amount),2) AS "Avg_Purchase_amount"
FROM customer
GROUP BY category 
ORDER BY SUM(purchase_amount) DESC ;

-- Q5. What is the revenue contribution of each age group?
SELECT age_group, SUM(purchase_amount) AS TOTAL_REVENUE
FROM customer
GROUP BY age_group
ORDER BY SUM(purchase_amount) DESC;

-- *Product Analysis* --

-- Q1. Which are the top 5 products with the highest average review rating?
SELECT item_purchased, ROUND(AVG(review_rating), 3) AS "Average Review rating"
FROM customer
GROUP BY item_purchased
ORDER BY AVG(review_rating) DESC
LIMIT 5;

-- Q2. Which 5 products have the highest percentage of purchases with discounts applied?
SELECT item_purchased, 
	ROUND(100 * SUM(CASE WHEN discount_applied = "Yes" THEN 1 ELSE 0 END) / COUNT(*), 2)AS "Percentage"
FROM customer
GROUP BY item_purchased
ORDER BY Percentage DESC
LIMIT 5;

-- Q3. What are the top 3 most purchased products within each category? 
WITH CTE AS (SELECT category, item_purchased, COUNT(*) AS TOTAL, 
ROW_NUMBER() OVER(PARTITION BY category ORDER BY COUNT(*) DESC) AS RNK
FROM customer
GROUP BY category, item_purchased
ORDER BY category )

SELECT RNK, category, item_purchased, TOTAL
FROM CTE
WHERE RNK <=3;

-- Q4. Do discounts actually increase the average purchase amount?
SELECT
    discount_applied,
    COUNT(customer_id) AS Total_Purchases,
    ROUND(AVG(purchase_amount), 2) AS Avg_Purchase_Amount,
    ROUND(SUM(purchase_amount), 2) AS Total_Revenue
FROM customer
GROUP BY discount_applied;

-- *Customer Behavior* --

-- Q1. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment.
 
WITH cte as (SELECT customer_id, previous_purchases,
	(CASE WHEN previous_purchases = 1 THEN "NEW"
		WHEN previous_purchases BETWEEN 2 AND 10 THEN "RETURNING"
		ELSE "LOYAL" END) as "Customer_Segment"
FROM customer)
SELECT Customer_Segment, COUNT(*) AS "No._of_customer"
FROM cte
GROUP BY Customer_Segment;

-- Q2. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT subscription_status, COUNT(customer_id) AS "Repeat_Customers", 
	ROUND(100.0 * COUNT(customer_id) / (SELECT COUNT(customer_id) FROM customer WHERE previous_purchases > 5), 2) AS "In_Percentage"
FROM CUSTOMER 
WHERE previous_purchases > 5
GROUP BY subscription_status;

-- Q3. Does purchase frequency affect customer spending?
SELECT frequency_of_purchases,
    ROUND(AVG(purchase_amount), 2) AS Avg_Purchase_Amount,
    ROUND(SUM(purchase_amount), 2) AS Total_Revenue
FROM customer
GROUP BY frequency_of_purchases
ORDER BY Avg_Purchase_Amount DESC;

-- *Operations & Preferences* -- 

-- Q1. Compare the average Purchase Amounts between Standard and Express Shipping.
 SELECT shipping_type, ROUND(AVG(purchase_amount), 3) AS "Average Purchase Amount"
 FROM customer
 WHERE shipping_type in ("Express", "Standard")
 GROUP BY shipping_type;
 
 -- Q2. Which payment methods generate the most revenue?
 SELECT payment_method,
	COUNT(*) AS Total_Transaction,
	ROUND(SUM(purchase_amount), 2) AS Total_Revenue,
	ROUND(100 * SUM(purchase_amount) / (select SUM(purchase_amount) from customer), 2) AS "In_Pecentage"
 FROM customer
 GROUP BY payment_method
 ORDER BY Total_Revenue DESC;
 
 -- Q3. Which locations generate the most revenue?
 
